POST http://localhost:3001/api/links/
Content-Type: application/json

{
    "code":"code",
    "url":"https://app.rocketseat.com.br/"
}

###

GET http://localhost:3000/api/links/


###

GET   http://localhost:3000/Rocksteat

###

GET   http://localhost:3000/api/metrics


